export const THSarabunBase64 =
"AAEAAAARAQAABAAQR0RFRqcXo5gAAAC8AAAAYGNtYXDpV7bFAAABHAAAAFRnYXNwAAAAEAAAAXgAAAAIZ2x5ZlLw0M4AAAF4AAABfGhlYWQKZ2XnAAACWAAAADZoaGVhB7gDmwAAApwAAAAkaG10eB8gA2oAAAK8AAAAGGxvY2EAKgC4AAAC2AAAABptYXhwAAwAFgAAAtwAAAAgbmFtZQK8D7EAAAL8AAAB5nBvc3QAAwAAAAAE4AAAACBwcmVwAAEAAgAABPAAAAAEd2FzZgAAAAEAAATwAAAACGZwZ20AAAAAAAABAAAABgAAAAEAAAAA";

export const loadThaiFont = (pdf: any) => {
  pdf.addFileToVFS("THSarabun.ttf", THSarabunBase64);
  pdf.addFont("THSarabun.ttf", "THSarabun", "normal");
  pdf.setFont("THSarabun");
};